target("_C")
    add_rules("python.module")
    set_targetdir(path.join(os.projectdir(), "extension_cpp"))
    add_files("csrc/muladd.cpp")
    add_cuda_files("csrc/cuda/muladd.cu")
    add_packages("pytorch", "openmp")
